version: "3.2"

services: 
    pleasework :
        image: jetty:9.4-jre11
        ports: 
        - "8080:8080"
        volumes:
        - ./target/livedemo-1.0-SNAPSHOT.war:/var/lib/jetty/webapps/root.war
